### ISSUE TITLE
Support type comments (PEP 484)

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/flake8-annotations#36]
Add the ability to process type comments in addition to annotations, [per PEP 484](https://www.python.org/dev/peps/pep-0484/#type-comments). Example:
```python
def some_func(arg1, arg2, arg3=True):
    # type: (Optional[str], int, bool) -> Optional[str]
    ...
```

Rationale/use cases
* Improves "out of the box" support and encourages migration for projects moving from Python 2 to Python 3
* Projects that don't have annotations for other reasons (compatibility, DSLs, performance)
* Extension modules
* Modules that use annotations for other purposes

Note: mypy supports type comments, so it may have some parsing code that could be adapted.

**Comment by sco1** [comment]
This may be fairly painlessly implemented by changing to [`typed-ast`](https://github.com/python/typed_ast):

> Unlike `ast`, the parsers in `typed_ast` include PEP 484 type comments and are independent of the version of Python under which they are run. The `typed_ast` parsers produce the standard Python AST (plus type comments), and are both fast and correct, as they are based on the CPython 2.7 and 3.7 parsers. `typed_ast` runs on CPython 3.5-3.8 on Linux, OS X and Windows.

With a caveat for 3.8+:

> `typed_ast` will not be updated to support parsing Python 3.8 and newer. Instead, it is recommended to use the stdlib `ast` module there, which has been augmented to support extracting type comments and has limited support for parsing older versions of Python 3.

In theory, we should be able to do a drop-in replacement now, loading the file ourselves rather than getting it from flake8, and then evaluate a version-based conditional for Python 3.8+.

**Comment by sco1** [comment]
To the 3.8+ caveat, it looks like we eventually might not have to worry about it. Per https://gitlab.com/pycqa/flake8/issues/118 and https://github.com/PyCQA/pyflakes/pull/400, this should make its way into `flake8` at some point in the near future.

**Comment by sco1** [comment]
I've added preliminary handling for PEP 484-style type comments in https://github.com/python-discord/flake8-annotations/tree/type-comment-investigation

This seems to function adequately for the above toy example, but need to build up a defensible test suite in order to ensure accuracy with real-world code.

**Comment by GhostofGoes** [comment]
Yeah, I did some digging around last night and `typed_ast` seems to be the best solution (and is also what mypy uses).

Technically having both runtime annotations and comment annotations is a violation of the PEP (and mypy considors it a violation). Is that something worth warning about?

Example: 
```python
def hello(jonny: str, fred: str) -> Optional[str]:
    # type: (str, str) -> Optional[str]
    ...
```
