### ISSUE TITLE
Support stub files (PEP 484)

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/flake8-annotations#37]
Add the ability to read type information from a stub file, [per PEP 484](https://www.python.org/dev/peps/pep-0484/#stub-files). This goes somewhat in hand with issue #36 and there is likely some overlap (namely with parsing).

Rationale/use cases (from PEP 484)

- Extension modules
- Third-party modules whose authors have not yet added type hints
- Standard library modules for which type hints have not yet been written
- Modules that must be compatible with Python 2 and 3
- Modules that use annotations for other purposes

**Comment by sco1** [comment]
After some initial poking around, the scope of this may be beyond what can sanely be accomplished with flake8 in its current state.

The primary barrier here is that flake8 operates on a per-file basis and there's no way (at least that I can determine) to persist information between files. This torpedoes my initial thought of matching `*.py` files with their corresponding `*.pyi` in order to identify which definitions in the `*.py` file are missing annotations in the stub. While we can likely adequately lint the stub with minor changes (this is kinda what our testing suite does), I'm not sure if that provides meaningful insight into the stub's coverage of the corresponding `*.py` file.

[`flakei-pyi`](https://github.com/ambv/flake8-pyi) appears to inject stub support into flake8, but does so by overloading Pyflakes & its integration with flake8. This may be a sufficient answer to the general question of stub support outside of going to mypy. Though it looks like it may just be linting the stub itself, I haven't had the chance to try out this plugin to see how well `flake8-annotations` plays. Browsing the source it appears to involve a not insignificant amount of work that I'm not sure we'd be comfortable maintaining, and given the issue raised in the first paragraph may not be helpful at all.

**Comment by GhostofGoes** [comment]
That makes sense. Expanding this extension beyond on regular source code (`.py` files) will likely result in maintenance headaches in the future, especially when there's a major Python release (like 3.8 coming up soon). The existing `flake8-pyi` extension is probably the more logical place for this feature. Going to go ahead and close this unless you think otherwise.
